// app/[locale]/layout.tsx
import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";
import React from "react";
import "react-toastify/dist/ReactToastify.css";
import Loading from "./loading";
import { getMessages } from "next-intl/server";
import { Providers } from "../../provider/providers";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/authOptions";

export const metadata: Metadata = {
  title: "Tender Admin",
  description: "Generated by Grandmart",
};

export async function generateStaticParams() {
  return [{ locale: "en" }, { locale: "az" }, { locale: "ru" }];
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { locale } = params;
  const messages = await getMessages();
  const session = await getServerSession(authOptions);
  
  return (
    <html lang={locale}>
      <body suppressHydrationWarning={true} className="custom-scrollbar">
        <div className="dark:bg-boxdark-2 dark:text-bodydark">
          <Providers locale={locale} messages={messages} session={session}>
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </Providers>
        </div>
      </body>
    </html>
  );
}